
name: Snyc to S3
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "github_action/workflow" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Sync with S3
        run: aws s3 sync . s3://[thanosql-tutorial]

